version: '3.7'

services:
  web:
    image: "myproject:dev"

    build:
      target: development_build
      context: ./app
      args:
        DJANGO_ENV: development
    command: python -Wd manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./config/.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  

volumes:
  postgres_data: